project:
  type: website

website:
  title: Tucson Crime Data Analysis 
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-F24/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Crime Trend Analysis
        href: https://hitarthbharadaz.shinyapps.io/dashboard-2/
      - text: Crime GeoSpatial Analysis
        href: https://hitarthbharadaz.shinyapps.io/dashboard-1/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
