project:
  type: website

website:
  title: "<img src='/images/tucson_logo.jpg' alt='Tucson Logo' style='width: 2.7em; height: 2.3em; border-radius: 20%;'> <b> Tucson Crime Data Analysis</b>"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-F24/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Dashboard
        href: dashboard.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto