---
title: "Question 1 Visualization"
author:
  - name: "VIZards"
    affiliations:
      - name: "College of Information, University of Arizona"
description: "Tucson Police Reported Crime Data Analysis"
format: dashboard
runtime: shiny
execute:
  warning: false
  echo: false
---


```{r include=FALSE}
if(!require(pacman))
  install.packages("pacman")

pacman::p_load(tidyverse,
               dplyr,
               tigris,
               sf,
               ggplot2,
               scales,
               shiny,
               tmap,
               colorspace,
               shinythemes,
               plotly)

options(width = 65)
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 0.618,
  fig.retina = 3,
  fig.align = "center",
  dpi = 300
)
```

```{r}
crime_data <- read.csv("./data/Tucson_Police_Reported_Crimes.csv")
tucson_wards <- st_read("Wards_-_City_of_Tucson.geojson") %>%
  mutate(Ward = as.character(WARD))

crime_data <- crime_data %>%
  mutate(
    UCRDescription = str_replace(UCRDescription, "^[0-9]+ - ", ""),
    UCRDescription = str_to_title(UCRDescription),
    Year = as.numeric(Year)
  )

```


```{r}
ui <- fillPage(
  theme = shinytheme("cosmo"),
  
  tags$style(HTML("
    body {
      background-color: #f4f6f9;
      font-family: 'Arial', sans-serif;
    }
    .sidebar {
      background-color: #ffffff;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      padding: 15px;
      margin-right: 10px;
    }
    .sidebar h4, .sidebar label {
      color: #333333;
      font-weight: bold;
    }
    .main-panel {
      background-color: #ffffff;
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .navbar {
      background-color: #007bff;
      color: #ffffff;
      border-radius: 0 0 8px 8px;
      padding: 10px 20px;
      font-size: 18px;
      text-align: center;
      font-weight: bold;
    }
    footer {
      text-align: center;
      color: #888;
      font-size: 14px;
      margin-top: 20px;
      padding: 10px;
    }
    footer a {
      color: #007bff;
      text-decoration: none;
    }
    footer a:hover {
      text-decoration: underline;
    }
  ")),

  titlePanel(tags$div(
    style = "color: black; padding: 15px; border-radius: 8px; text-align: center;",
    tags$h1("Tucson Crime Analysis", style = "margin: 0;")
  )),
  
  sidebarLayout(
    sidebarPanel(
      class = "sidebar",
      width = 3,
      tags$h4("Filters", style = "text-align: center; margin-bottom: 15px;"),
      selectInput(
        inputId = "year_filter",
        label = "Select Year:",
        choices = c("All", sort(unique(crime_data$Year))),
        selected = "All"
      ),
      selectInput(
        inputId = "crime_type_filter",
        label = "Select Crime Type:",
        choices = c("All", sort(unique(crime_data$UCRDescription))),
        selected = "All"
      )
    ),
    mainPanel(
      class = "main-panel",
      width = 9,
      tabsetPanel(
        tabPanel("Geo Distribution", tmapOutput("crime_map", height = "600px", width = "100%")),
        tabPanel("Distribution over Police Divisions", plotlyOutput("bar_chart", height = "600px", width = "100%"))
      )
    )
  ),
  
  tags$footer(
    tags$a(
      href = "https://info-526-f24.github.io/project-01-VIZards/",
      "Visit Our Website - VIZards"
    ),
    style = "margin-top: 20px; background-color: #f4f6f9; padding: 10px;"
  )
)
```


```{r}
server <- function(input, output, session) {

  filtered_data <- reactive({
    data <- crime_data
    if (input$year_filter != "All") {
      data <- data %>% filter(Year == input$year_filter)
    }
    if (input$crime_type_filter != "All") {
      data <- data %>% filter(UCRDescription == input$crime_type_filter)
    }
    data %>%
      group_by(Ward) %>%
      summarise(CrimeCount = n(), .groups = "drop") %>%
      mutate(Ward = as.character(Ward))
  })

  merged_data <- reactive({
    tucson_wards %>%
      left_join(filtered_data(), by = "Ward") %>%
      mutate(CrimeCount = as.numeric(CrimeCount))
  })

  crime_colors <- c(
    "Homicide" = "#d78f7e",
    "Sexual Assault" = "#111210",
    "Robbery" = "#dce0c5",
    "Assault, Aggravated" = "#80607f",
    "Burglary" = "#ffa07a",
    "Larceny" = "#91c4b3",
    "GTA" = "#8b4513",
    "Other" = "gray"
  )

  output$crime_map <- renderTmap({
    tmap_mode("view")
    tm_shape(merged_data()) +
      tm_fill(
        "CrimeCount",
        palette = "Reds",
        title = "Incidents",
        popup.vars = c("Incidents :  " = "CrimeCount"),
        border.col = "black", border.alpha = .5,
        id = "Label"
      ) +
      tm_borders() +
      tm_layout(title = "Tucson Crime Analysis") +
      tm_text("Label") +
      tm_legend(position = c("left", "bottom")) +
      tm_layout(frame = FALSE)
  })

  processed_data <- reactive({
    data <- crime_data
    if (input$year_filter != "All") {
      data <- data %>% filter(Year == input$year_filter)
    }
    data %>%
      filter(Division != "" & !is.na(Division)) %>%
      mutate(UCRDescription = ifelse(UCRDescription %in% names(crime_colors), UCRDescription, "Other")) %>%
      group_by(Division, UCRDescription) %>%
      summarise(CrimeCount = n(), .groups = "drop") %>%
      group_by(Division) %>%
      mutate(
        Percentage = CrimeCount / sum(CrimeCount) * 100,
        Division = factor(Division, levels = c("Midtown", "South", "West", "East"))
      ) %>%
      arrange(desc(CrimeCount))
  })


  output$bar_chart <- renderPlotly({
  data <- processed_data() %>%
    filter(Division != "NA") %>%
    group_by(Division) %>%
    arrange(desc(CrimeCount)) %>%
    mutate(UCRDescription = fct_reorder(UCRDescription, CrimeCount, .desc = TRUE)) %>%
    ungroup()

  bar_colors <- setNames(
    if (input$crime_type_filter == "All") {
      crime_colors 
    } else {
      ifelse(
        names(crime_colors) == input$crime_type_filter,
        crime_colors, 
        scales::alpha(crime_colors, 0.3) 
      )
    },
    names(crime_colors) 
  )

ggplot_chart <- ggplot(data, aes(
    x = Division,
    y = CrimeCount,
    fill = UCRDescription,
    text = paste(
      "Division:", Division,
      "<br>Crime Type:", UCRDescription,
      "<br>Incidents:", scales::comma(CrimeCount)
    )
  )) +
  geom_bar(
    stat = "identity",
    position = position_dodge(width = 0.9),
    color = "black"
  ) +
  scale_y_log10(labels = scales::comma) +
  scale_fill_manual(values = bar_colors) +
  labs(
    title = paste(
      "Distribution of", if (input$crime_type_filter == "All") "All" else input$crime_type_filter,
      "Crimes across Tucson Divisions"
    ),
    x = "Division",
    y = "Incident Count",
    fill = NULL,
    caption = "Source: City of Tucson"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 12, hjust = 1),
    axis.text.y = element_text(size = 12),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.spacing.x = unit(1, "cm"),
    legend.title = element_blank(),
    legend.text = element_text(family = "sans", size = 12),
    legend.key.width = unit(1.5, "cm"),
    legend.key.height = unit(0.5, "cm"),
    plot.title = element_text(
      hjust = 0.5,
      vjust = 2,
      size = 15
    ),
    plot.margin = unit(c(1.2, 1.2, 1.2, 1.2), "cm"),
    panel.border = element_rect(color = "grey80", fill = NA)
  ) +
  guides(fill = guide_legend(label.position = "top", nrow = 1))

  ggplotly(ggplot_chart, tooltip = "text") %>%
    layout(
      legend = list(
        orientation = "h",
        x = 0.5,
        y = -0.2,
        xanchor = "center",
        yanchor = "top",
        itemwidth = 50,
        font = list(size = 12)
      ),
      title = list(
        text = paste(
          "Distribution of", if (input$crime_type_filter == "All") "All" else input$crime_type_filter,
          "Crimes across Police Divisions"
        ),
        x = 0.5
      )
    )
  })
}

shinyApp(ui = ui, server = server)
```